package kebunku;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class RegisterPlant extends javax.swing.JFrame {
    Connection conn = null;
    Statement sta = null;

    /**
     * Creates new form RegisterPlant
     */
    public RegisterPlant() {
        initComponents();
    }
    
    private void HapusLayar(){
        UserRegrisTF.setText("");
        PassRegrisPF.setText("");
        UPassRegrisPF.setText("");
        NamaRegrisTF.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XRegrisLabel = new javax.swing.JPanel();
        RegrisLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NamaRegrisTF = new javax.swing.JTextField();
        UserRegrisTF = new javax.swing.JTextField();
        PassRegrisPF = new javax.swing.JPasswordField();
        UPassRegrisPF = new javax.swing.JPasswordField();
        HelloLabel = new javax.swing.JLabel();
        RegrisButton = new javax.swing.JButton();
        KembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        XRegrisLabel.setBackground(new java.awt.Color(51, 255, 51));

        RegrisLabel.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        RegrisLabel.setText("REGISTRASI KEBUN");

        javax.swing.GroupLayout XRegrisLabelLayout = new javax.swing.GroupLayout(XRegrisLabel);
        XRegrisLabel.setLayout(XRegrisLabelLayout);
        XRegrisLabelLayout.setHorizontalGroup(
            XRegrisLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, XRegrisLabelLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(RegrisLabel)
                .addGap(102, 102, 102))
        );
        XRegrisLabelLayout.setVerticalGroup(
            XRegrisLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, XRegrisLabelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(RegrisLabel)
                .addGap(27, 27, 27))
        );

        getContentPane().add(XRegrisLabel);
        XRegrisLabel.setBounds(8, 13, 480, 90);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Nama ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Konfirmasi Password");

        HelloLabel.setFont(new java.awt.Font("Yu Gothic Medium", 1, 20)); // NOI18N
        HelloLabel.setText("SELAMAT DATANG");

        RegrisButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        RegrisButton.setText("REGISTRASI");
        RegrisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegrisButtonActionPerformed(evt);
            }
        });

        KembaliButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        KembaliButton.setText("KEMBALI");
        KembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegrisButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaRegrisTF)
                            .addComponent(UserRegrisTF)
                            .addComponent(PassRegrisPF)
                            .addComponent(UPassRegrisPF))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(KembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HelloLabel)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(HelloLabel)
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamaRegrisTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UserRegrisTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PassRegrisPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UPassRegrisPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegrisButton)
                    .addComponent(KembaliButton))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 480, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegrisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegrisButtonActionPerformed
        // TODO add your handling code here:
        try{
            if(UserRegrisTF.getText().equals("")|| PassRegrisPF.getPassword().equals("")|| 
                    NamaRegrisTF.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Data Anda Tidak Diperbolehkan Kosong!", "Pesan", JOptionPane.ERROR_MESSAGE);
                HapusLayar();  
            } else{
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/db_garden", "root", "");
                sta = conn.createStatement();
                String simpan = "insert into tbl_login values('"+UserRegrisTF.getText()+"', '"
                        + String.valueOf(PassRegrisPF.getPassword())+"','"+NamaRegrisTF.getText()+"')";
                sta = conn.createStatement();
                int SA = sta.executeUpdate(simpan);
                JOptionPane.showMessageDialog(this, "Regristrasi Anda Berhasil!");
                this.setVisible(false);
                new LoginPlant().setVisible(true);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Akun Anda Sudah Ada/Duplikat Akun", "Pesan", JOptionPane.WARNING_MESSAGE);
            
            HapusLayar();      
        }
    }//GEN-LAST:event_RegrisButtonActionPerformed

    private void KembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginPlant().setVisible(true);
    }//GEN-LAST:event_KembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPlant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JButton KembaliButton;
    private javax.swing.JTextField NamaRegrisTF;
    private javax.swing.JPasswordField PassRegrisPF;
    private javax.swing.JButton RegrisButton;
    private javax.swing.JLabel RegrisLabel;
    private javax.swing.JPasswordField UPassRegrisPF;
    private javax.swing.JTextField UserRegrisTF;
    private javax.swing.JPanel XRegrisLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
